// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaSupply.Data;

#nullable disable

namespace PharmaSupply.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810184755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaSupply.Data.AdminNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("PharmaSupply.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "medication",
                            Name = "Ağrı Kesiciler"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "nutrition",
                            Name = "Vitamin & Takviye"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "dermatology",
                            Name = "Dermokozmetik"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "health_and_safety",
                            Name = "Medikal Ürünler"
                        });
                });

            modelBuilder.Entity("PharmaSupply.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PharmaSupply.Data.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PharmaSupply.Data.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsLicenseActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MonthlyRedPrescriptionQuota")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<int>("UsedRedPrescriptionQuota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pharmacies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 12500m,
                            CreditLimit = 75000m,
                            IsLicenseActive = true,
                            LicenseNumber = "ECZ-34001",
                            MonthlyRedPrescriptionQuota = 100,
                            Name = "Şifa Eczanesi",
                            UsedRedPrescriptionQuota = 0
                        });
                });

            modelBuilder.Entity("PharmaSupply.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveIngredient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<int>("PrescriptionType")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveIngredient = "Parasetamol",
                            CategoryId = 1,
                            Description = "Paraset 500 mg, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/640x520/f0f6ff/0047ab?text=Paraset%20500%20mg",
                            IsBestSeller = true,
                            Kind = 0,
                            Name = "Paraset 500 mg",
                            PrescriptionType = 0,
                            Stock = 240,
                            UnitPrice = 68.50m
                        },
                        new
                        {
                            Id = 2,
                            ActiveIngredient = "İbuprofen",
                            CategoryId = 1,
                            Description = "İbucold Plus, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2026, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/640x520/f0f6ff/0047ab?text=%C4%B0bucold%20Plus",
                            IsBestSeller = true,
                            Kind = 0,
                            Name = "İbucold Plus",
                            PrescriptionType = 0,
                            Stock = 42,
                            UnitPrice = 124.90m
                        },
                        new
                        {
                            Id = 3,
                            ActiveIngredient = "Omega-3",
                            CategoryId = 2,
                            Description = "Omega 3 Forte, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/640x520/f0f6ff/0047ab?text=Omega%203%20Forte",
                            IsBestSeller = true,
                            Kind = 1,
                            Name = "Omega 3 Forte",
                            PrescriptionType = 0,
                            Stock = 85,
                            UnitPrice = 289.00m
                        },
                        new
                        {
                            Id = 4,
                            ActiveIngredient = "Dekspantenol",
                            CategoryId = 3,
                            Description = "Dermacare Krem, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/640x520/f0f6ff/0047ab?text=Dermacare%20Krem",
                            IsBestSeller = false,
                            Kind = 0,
                            Name = "Dermacare Krem",
                            PrescriptionType = 0,
                            Stock = 33,
                            UnitPrice = 176.50m
                        },
                        new
                        {
                            Id = 5,
                            ActiveIngredient = "Diazepam",
                            CategoryId = 1,
                            Description = "Diazepam 5 mg, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/640x520/f0f6ff/0047ab?text=Diazepam%205%20mg",
                            IsBestSeller = false,
                            Kind = 0,
                            Name = "Diazepam 5 mg",
                            PrescriptionType = 2,
                            Stock = 80,
                            UnitPrice = 92.25m
                        },
                        new
                        {
                            Id = 6,
                            ActiveIngredient = "Morfin",
                            CategoryId = 4,
                            Description = "Morfin Ampul, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2028, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/640x520/f0f6ff/0047ab?text=Morfin%20Ampul",
                            IsBestSeller = false,
                            Kind = 0,
                            Name = "Morfin Ampul",
                            PrescriptionType = 1,
                            Stock = 65,
                            UnitPrice = 440.00m
                        });
                });

            modelBuilder.Entity("PharmaSupply.Data.Order", b =>
                {
                    b.HasOne("PharmaSupply.Data.Pharmacy", "Pharmacy")
                        .WithMany("Orders")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("PharmaSupply.Data.OrderItem", b =>
                {
                    b.HasOne("PharmaSupply.Data.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSupply.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaSupply.Data.Product", b =>
                {
                    b.HasOne("PharmaSupply.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmaSupply.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PharmaSupply.Data.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PharmaSupply.Data.Pharmacy", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
