// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaSupply.Data;

#nullable disable

namespace PharmaSupply.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaSupply.Data.AdminNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("PharmaSupply.Data.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PharmacyId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("PharmaSupply.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "medication",
                            Name = "Ağrı Kesiciler"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "nutrition",
                            Name = "Vitamin & Takviye"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "dermatology",
                            Name = "Dermokozmetik"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "health_and_safety",
                            Name = "Medikal Ürünler"
                        });
                });

            modelBuilder.Entity("PharmaSupply.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PharmaSupply.Data.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PharmaSupply.Data.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsLicenseActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MonthlyRedPrescriptionQuota")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<int>("UsedRedPrescriptionQuota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pharmacies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 12500m,
                            CreditLimit = 75000m,
                            IsLicenseActive = true,
                            LicenseNumber = "ECZ-34001",
                            MonthlyRedPrescriptionQuota = 100,
                            Name = "Şifa Eczanesi",
                            UsedRedPrescriptionQuota = 0
                        });
                });

            modelBuilder.Entity("PharmaSupply.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveIngredient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<int>("PrescriptionType")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveIngredient = "Parasetamol",
                            CategoryId = 1,
                            Description = "Paraset 500 mg, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/analgesics.png",
                            IsBestSeller = true,
                            Kind = 0,
                            Name = "Paraset 500 mg",
                            PrescriptionType = 0,
                            Stock = 240,
                            UnitPrice = 68.50m
                        },
                        new
                        {
                            Id = 2,
                            ActiveIngredient = "İbuprofen",
                            CategoryId = 1,
                            Description = "İbucold Plus, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2026, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/analgesics.png",
                            IsBestSeller = true,
                            Kind = 0,
                            Name = "İbucold Plus",
                            PrescriptionType = 0,
                            Stock = 42,
                            UnitPrice = 124.90m
                        },
                        new
                        {
                            Id = 3,
                            ActiveIngredient = "Omega-3",
                            CategoryId = 2,
                            Description = "Omega 3 Forte, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/supplements.png",
                            IsBestSeller = true,
                            Kind = 1,
                            Name = "Omega 3 Forte",
                            PrescriptionType = 0,
                            Stock = 85,
                            UnitPrice = 289.00m
                        },
                        new
                        {
                            Id = 4,
                            ActiveIngredient = "Dekspantenol",
                            CategoryId = 3,
                            Description = "Dermacare Krem, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/dermocosmetics.png",
                            IsBestSeller = false,
                            Kind = 0,
                            Name = "Dermacare Krem",
                            PrescriptionType = 0,
                            Stock = 33,
                            UnitPrice = 176.50m
                        },
                        new
                        {
                            Id = 5,
                            ActiveIngredient = "Diazepam",
                            CategoryId = 1,
                            Description = "Diazepam 5 mg, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/analgesics.png",
                            IsBestSeller = false,
                            Kind = 0,
                            Name = "Diazepam 5 mg",
                            PrescriptionType = 2,
                            Stock = 80,
                            UnitPrice = 92.25m
                        },
                        new
                        {
                            Id = 6,
                            ActiveIngredient = "Morfin",
                            CategoryId = 4,
                            Description = "Morfin Ampul, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2028, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/medical-supplies.png",
                            IsBestSeller = false,
                            Kind = 0,
                            Name = "Morfin Ampul",
                            PrescriptionType = 1,
                            Stock = 65,
                            UnitPrice = 440.00m
                        },
                        new
                        {
                            Id = 7,
                            ActiveIngredient = "Naproksen Sodyum",
                            CategoryId = 1,
                            Description = "Naproksen Forte 550 mg, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2028, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/analgesics.png",
                            IsBestSeller = true,
                            Kind = 0,
                            Name = "Naproksen Forte 550 mg",
                            PrescriptionType = 0,
                            Stock = 118,
                            UnitPrice = 148.75m
                        },
                        new
                        {
                            Id = 8,
                            ActiveIngredient = "Asetilsalisilik Asit",
                            CategoryId = 1,
                            Description = "Migra Relief 250 mg, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/analgesics.png",
                            IsBestSeller = false,
                            Kind = 0,
                            Name = "Migra Relief 250 mg",
                            PrescriptionType = 0,
                            Stock = 76,
                            UnitPrice = 86.40m
                        },
                        new
                        {
                            Id = 9,
                            ActiveIngredient = "Ketoprofen",
                            CategoryId = 1,
                            Description = "Ketoprofen Jel, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/analgesics.png",
                            IsBestSeller = false,
                            Kind = 0,
                            Name = "Ketoprofen Jel",
                            PrescriptionType = 0,
                            Stock = 39,
                            UnitPrice = 132.20m
                        },
                        new
                        {
                            Id = 10,
                            ActiveIngredient = "Kolekalsiferol",
                            CategoryId = 2,
                            Description = "Vitamin D3 1000 IU, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2028, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/supplements.png",
                            IsBestSeller = true,
                            Kind = 1,
                            Name = "Vitamin D3 1000 IU",
                            PrescriptionType = 0,
                            Stock = 164,
                            UnitPrice = 214.90m
                        },
                        new
                        {
                            Id = 11,
                            ActiveIngredient = "Magnezyum Sitrat",
                            CategoryId = 2,
                            Description = "Magnezyum Complex, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2028, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/supplements.png",
                            IsBestSeller = false,
                            Kind = 1,
                            Name = "Magnezyum Complex",
                            PrescriptionType = 0,
                            Stock = 91,
                            UnitPrice = 319.50m
                        },
                        new
                        {
                            Id = 12,
                            ActiveIngredient = "Lactobacillus Acidophilus",
                            CategoryId = 2,
                            Description = "Probiyotik Balance, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/supplements.png",
                            IsBestSeller = true,
                            Kind = 1,
                            Name = "Probiyotik Balance",
                            PrescriptionType = 0,
                            Stock = 58,
                            UnitPrice = 384.00m
                        },
                        new
                        {
                            Id = 13,
                            ActiveIngredient = "%10 Üre",
                            CategoryId = 3,
                            Description = "Urea Repair Losyon, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/dermocosmetics.png",
                            IsBestSeller = false,
                            Kind = 1,
                            Name = "Urea Repair Losyon",
                            PrescriptionType = 0,
                            Stock = 72,
                            UnitPrice = 268.75m
                        },
                        new
                        {
                            Id = 14,
                            ActiveIngredient = "Organik UV Filtreleri",
                            CategoryId = 3,
                            Description = "Sun Protect SPF 50+, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2028, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/dermocosmetics.png",
                            IsBestSeller = true,
                            Kind = 1,
                            Name = "Sun Protect SPF 50+",
                            PrescriptionType = 0,
                            Stock = 105,
                            UnitPrice = 449.90m
                        },
                        new
                        {
                            Id = 15,
                            ActiveIngredient = "Niasinamid",
                            CategoryId = 3,
                            Description = "Niacinamide Serum, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/dermocosmetics.png",
                            IsBestSeller = false,
                            Kind = 1,
                            Name = "Niacinamide Serum",
                            PrescriptionType = 0,
                            Stock = 46,
                            UnitPrice = 398.50m
                        },
                        new
                        {
                            Id = 16,
                            ActiveIngredient = "Medikal Cihaz",
                            CategoryId = 4,
                            Description = "Dijital Ateş Ölçer, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2029, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/medical-supplies.png",
                            IsBestSeller = true,
                            Kind = 1,
                            Name = "Dijital Ateş Ölçer",
                            PrescriptionType = 0,
                            Stock = 130,
                            UnitPrice = 245.00m
                        },
                        new
                        {
                            Id = 17,
                            ActiveIngredient = "Enzimatik Test Stribi",
                            CategoryId = 4,
                            Description = "Glikoz Test Stribi 50'li, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2027, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/medical-supplies.png",
                            IsBestSeller = false,
                            Kind = 1,
                            Name = "Glikoz Test Stribi 50'li",
                            PrescriptionType = 0,
                            Stock = 88,
                            UnitPrice = 525.40m
                        },
                        new
                        {
                            Id = 18,
                            ActiveIngredient = "Steril Pamuklu Gaz",
                            CategoryId = 4,
                            Description = "Steril Gaz Kompres 100'lü, eczane ve sağlık kuruluşlarının profesyonel kullanımına sunulan güvenilir üründür.",
                            ExpirationDate = new DateTime(2028, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/products/medical-supplies.png",
                            IsBestSeller = false,
                            Kind = 1,
                            Name = "Steril Gaz Kompres 100'lü",
                            PrescriptionType = 0,
                            Stock = 210,
                            UnitPrice = 184.90m
                        });
                });

            modelBuilder.Entity("PharmaSupply.Data.CartItem", b =>
                {
                    b.HasOne("PharmaSupply.Data.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSupply.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaSupply.Data.Order", b =>
                {
                    b.HasOne("PharmaSupply.Data.Pharmacy", "Pharmacy")
                        .WithMany("Orders")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("PharmaSupply.Data.OrderItem", b =>
                {
                    b.HasOne("PharmaSupply.Data.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSupply.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaSupply.Data.Product", b =>
                {
                    b.HasOne("PharmaSupply.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmaSupply.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PharmaSupply.Data.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PharmaSupply.Data.Pharmacy", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
